export const APPS = [
  {
    id: 'landing-page',
    name: 'Home',
    description: 'Internal tools landing page',
    url: 'https://tools.jtamerius.com',
    subdomain: 'tools',
    isPublic: true,
    requiredGroup: null,
  },
  {
    id: 'weather-app',
    name: 'Ensemble Weather',
    description: 'Multi-model ensemble forecasts for the Southwest US',
    url: 'https://weather.jtamerius.com',
    subdomain: 'weather',
    isPublic: true,
    requiredGroup: null,
  },
  {
    id: 'finance-app',
    name: 'Finance Tracker',
    description: 'Personal finance tracking and analysis',
    url: 'https://finance.jtamerius.com',
    subdomain: 'finance',
    isPublic: false,
    requiredGroup: 'member',
  },
  {
    id: 'globe-app',
    name: 'Interactive Globe',
    description: 'Real-time 3D Earth with day/night cycle, atmosphere, and interactive overlays',
    url: 'https://globe.jtamerius.com',
    subdomain: 'globe',
    isPublic: true,
    requiredGroup: null,
  },
]
